goldapp/urls.py
from django.urls import path
from . import views

app_name = 'goldapp'

urlpatterns = [
	path('', views.index, name = "index"),
	path('product/<int:id>', views.get_product, name="product"),
	path('about/', views.about, name="about"),
	path('contact/', views.contact, name="contact"),
	path('products', views.get_products, name="products"),
    path('category/<int:id>', views.get_product_category, name="category"),
    path('allproducts', views.allproducts, name="allproducts"),
    path('faq', views.faq, name="faq"),
    path('checkout', views.checkout, name="checkout"),
    path('delivery', views.delivery, name="delivery"),
    path('leylaninulduzlari', views.leylaninulduzlari, name="leylaninulduzlari"),
    path('set-language/', views.change_language, name="set_language"),

]

goldin/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
urlpatterns = i18n_patterns (
    path('admin/', admin.site.urls),
    path('search/', include('search.urls')),
    path('users/', include('users.urls')),
    path('',include("goldapp.urls")),
    prefix_default_language=False
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views

from . import views

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

goldapp/models.py
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth.models import User
# Create your models here.

# Slider
class Slider(models.Model):
	title = models.CharField(max_length=150, verbose_name='Title')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	slideimg = models.FileField(upload_to = "slide/", verbose_name='Slide image')

	class Meta:
		verbose_name = "Slider"
		verbose_name_plural = 'Sliders'

	def __str__(self):
		return self.title


class EnglishSlider(models.Model):
	title = models.CharField(max_length=150, verbose_name='Title')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	engslideimg = models.FileField(upload_to = "slide/", verbose_name='English slide image')

	class Meta:
		verbose_name = "English Slider"
		verbose_name_plural = 'English Sliders'

	def __str__(self):
		return self.title


# partnyor
class Partnyor(models.Model):
	title = models.CharField(max_length=150, verbose_name='Title')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	partnyorimg = models.FileField(upload_to = "partimg/", verbose_name='Partnyor Image')

	class Meta:
		verbose_name = "Partnyor"
		verbose_name_plural = 'Partnyors'

	def __str__(self):
		return self.title

# cataegory
class Category(models.Model):
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank = True, null=True, verbose_name='Parent')
    title = models.CharField(max_length=100, verbose_name='Title') 
    slug = AutoSlugField(populate_from='title', unique=True, null=False, editable=False, verbose_name = 'Slug')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title

    class Meta:
        unique_together = ('slug', 'parent',)
        verbose_name_plural = "categories"     
	# iç içə kateqoriya
    def __str__(self):                           
        full_path = [self.title]                  
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' -> '.join(full_path[::-1])  


# Product
class Product(models.Model):
	category = models.ForeignKey(Category, on_delete = models.CASCADE, verbose_name='Category')
	name = models.CharField(max_length = 100, verbose_name='Name')
	slug = models.SlugField(max_length=100, db_index=True, verbose_name='Slug')
	price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='Price')
	productimg = models.FileField(upload_to = "productimg/", verbose_name='Product image')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.IntegerField(default=0)
	description = models.TextField(blank=True, verbose_name='Description')
	is_approximate = models.BooleanField(verbose_name='Approximate', default=False)
	is_mainpage = models.BooleanField(verbose_name='Main page', default=False)

	class Meta:
		verbose_name = "Product"
		verbose_name_plural = "Products"

	def __str__(self):
	    return 'name={0}, category={1}'.format(self.name, self.category)

# Images
class Images(models.Model):
	product=models.ForeignKey(Product,on_delete=models.CASCADE, verbose_name='Product')
	title = models.CharField(max_length=50, verbose_name='Title')
	productimg=models.FileField(upload_to="productimg/", verbose_name='Product image')

	class Meta:
		verbose_name = "Image"
		verbose_name_plural = "Images"

	def __str__(self):
		return self.title

class ProductSlider(models.Model):
	title = models.CharField(max_length=150, verbose_name="Title")
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	prodslideimg = models.FileField(upload_to = "slide/", verbose_name="Product Slide Image")

	verbose_name = "Product Slider"
	verbose_name_plural = "Product Sliders"

	def __str__(self):
		return self.title

class ContactUs(models.Model):
	first_name = models.CharField(max_length=255, verbose_name='First Name', help_text='Max 255 character')
	email = models.EmailField(verbose_name='Email Address')
	telephone = models.CharField(max_length=20)
	message = models.TextField(verbose_name='Message')

	verbose_name = "Contact Us"
	verbose_name_plural = "Contact Us"

	def __str__(self):
		return self.first_name

class Faq(models.Model):
	question = models.TextField(verbose_name='Question')
	answer = models.TextField(verbose_name='Answer')
	is_mainpage = models.BooleanField(verbose_name='Main page', default=False)

	verbose_name = 'FAQ'
	verbose_name = 'FAQS'

	def __str__(self):
		return self.question

goldapp/forms.py
from django import forms

from .models import ContactUs
from django.forms import widgets

class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = '__all__'
        widgets = {
            'first_name': widgets.TextInput(attrs={'class': 'form-control', 'placeholder': 'Adınız'}),
            'email' : widgets.EmailInput(attrs={'class': 'form-control required-entry validate-email','placeholder': 'E-mail ünvanınız'} ),
            'telephone': widgets.TextInput(attrs={'class': 'form-control', 'value': '+994'}),
            'message': widgets.Textarea(attrs={'class': 'form-control', 'rows': 6, 'cols': 30, 'style': 'line-height: 1.5rem', 'placeholder': 'Müraciətiniz'} ),
        }

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        print(first_name)
        if len(first_name) < 2:
            raise forms.ValidationError("Adınızı düzgün daxil edin.")
        return first_name

    def clean_telephone(self):
        telephone = self.cleaned_data.get('telephone')
        print(telephone)
        if len(telephone) < 10 or len(telephone) > 20:
            raise forms.ValidationError("Telefon nömrənizi düzgün daxil edin.")
        return telephone
        

goldapp/views.py
from itertools import product
from sys import prefix
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from .models import *
from .forms import *
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse, HttpResponseRedirect



# Create your views here.
def index(request):
    mainproducts = Product.objects.filter(is_mainpage=True)
    dateproducts = Product.objects.order_by('-id')[:8]
    slide=Slider.objects.all()
    engslide = EnglishSlider.objects.all()
    # paginator=Paginator(mainproducts,1)
    page=request.GET.get('page')
    # newproducts=paginator.get_page(page)
    partnyor=Partnyor.objects.all()
    context={
        'dateproduct':dateproducts,
        "mainproduct":mainproducts,
        "slide":slide,
        "engslide": engslide,
        "partnyor":partnyor,
    }
    return render(request, 'index.html',context)


def allproducts(request):
    products_ = Product.objects.all()
    paginator = Paginator(products_, 20)
    page = request.GET.get('page')
    prod_slide = ProductSlider.objects.all()
    products = paginator.get_page(page)
    context = {
        'product':products,
        "prod_slide":prod_slide,
    }
    return render(request, "allproducts.html", context=context)


def about(request):

    return render(request, 'about.html')


def get_product(request,id):
    category = Category.objects.all()
    product = Product.objects.get(pk=id)
    images = Images.objects.filter(product_id=id)
    page = request.GET.get('page')
    #yorumları getirme
    context = {
        'product':product,
        'category':category,
        'images':images,
    }

    return render(request,"product.html",context=context)


# category
def get_products(request):
    # products = Product.objects.all()
    product_ = Product.objects.all()
    paginator = Paginator(product_, 3)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    # products=Product.objects.filter()
    return render(request, "category.html", {"prodcut":products})

# katoqoriyadakı paginton tıklayanda ona uyğun göstərir
def get_product_category(request, id):
    product_ = Product.objects.filter(category_id=id)
    paginator = Paginator(product_, 8)
    page = request.GET.get('page')
    product = paginator.get_page(page)
    return render(request, "category.html", {"product":product})


def contact(request):

    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('goldapp:contact')
        else:
            print(form.errors)
    else:
        form = ContactUsForm()

    context = {
        'title' : 'Contact Us',
        'form' : form,
    }

    return render(request, "contact.html", context=context)


def faq(request):
    faqs = Faq.objects.all()
    context ={
        'faqs': faqs
    }
    return render(request, "faq.html", context)


def checkout(request):
    return render(request, 'checkout.html')


def delivery(request):
    return render(request, 'delivery.html')


def change_language(request):
    if request.GET.get('lang') == 'az' or request.GET.get('lang') == 'en' or request.GET.get('lang') == 'default':
        # print(request.META.get('HTTP_REFERER'))
        path_list = request.META.get('HTTP_REFERER').split('/')
        # print(path_list)
        
        if request.GET.get('lang') == 'default':
            path_list.pop(3)
        else:
            path_list.insert(3, request.GET.get('lang'))
        path = '/'.join(path_list)
        # print(path)
        
        response = HttpResponseRedirect(path)
        response.set_cookie('django_language', request.GET['lang'])
        return response

def leylaninulduzlari(request):
    return render(request, 'star.html')

goldapp/templates/category.html
{% extends 'base.html' %}
{% load static i18n %}

{%block title %}{% translate 'Filterlənmiş məhsullar' %}{% endblock %}
{% block base %}
 <div class="container">
  <div class="row">
    {% for item in product %}
    <div class = 'col-lg-3 col-md-4 col-6'>
      <div class="col-lg-12 p-3 rounded-6 border my-3 posr">
        <a href="#" class="d-block text-center" data-bs-toggle="modal"
          data-bs-target="#productmodal"><img style="height: 200px;" src="{{ item.productimg.url }}" alt="product-image"
            class="w-100 mt-1 rounded_img d-inline-block" /></a>

        <div class="clearfix"></div>
        <div style="margin-top: 20px; height: 70px;">
        <h2 style="text-align: center;" >
          <a href="{% url 'goldapp:product' id=item.id %}"
            class="text-yellow item-name fw-600 lh-22  ls-0">{{ item.name}}
            <br />
           

          </a>
        </h2>
      </div>
      {% if item.is_approximate %}
        <div style="margin-top: 50px;" class="d-flex flex-row align-items-center justify-content-center">
          <h2 style="color: red; text-align: center;" class=" mb-0 ls-3 fw-700 ">
            {{ item.price }}  ₼ <span style="color: grey; font-size: 15px;">- dan</span>  
            
          </h2>
        </div>
        {% else %}
        <div style="margin-top: 50px;" class="d-flex flex-row align-items-center justify-content-center">
          <h2 style="color: red; text-align: center;" class=" mb-0 ls-3 fw-700 ">
            {{ item.price }}  ₼  
            
          </h2>
        </div>
        {% endif %}
       
      </div>
    </div>
    {% endfor %}

  </div>
 </div>

  {% if product|length > 0 %}
    <div class="d-pagination">
        <ul class="pagination justify-content-center">
      {% if product.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ product.previous_page_number }}"><i class="feather-chevron-left"></i></a>
        </li>
      {% endif %}
      {% for ord in product.paginator.page_range %}
        {% if product.number == ord %}
          <li class="page-item active">
            <span class="page-link">{{ ord }}
            </span>
          </li>
        {% elif ord > product.number|add:'-3' and ord < product.number|add:'3' %}
          <li class="page-item">
            <a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
          </li>

        {% endif %}

      {% endfor %}
       {% if product.has_next %}
       
        <li class="page-item">
          <a class="page-link" href="?page={{ product.paginator.num_pages }}"><i class="feather-chevron-right"></i></a>
        </li>
      {% endif %}
        </ul>
    </div>
    {% else %}
    <h3 class="text-center mt-5">{% translate 'Məhsul tapılmadı...' %}</h3>
    {% endif %}	 
<br>
{% endblock %}

goldapp/templates/index.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% translate 'Ana səhifə' %}{% endblock %}
{% block base %}
<style>
      @import url("https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap");
.accordion .contentbx .label::before {
    font-size: 1rem;
    color: white;
}

.faqsection {
  height: 100%;
  width: 80%;
  display: flex;
  /* flex-direction: column; */
  /* justify-content: center; */
  /* align-items: center; */
  /* text-align: center; */
  /* margin-top: 20px; */
  /* margin-bottom: 40px; */
  margin: 0 auto;
  /* padding: 15px; */
  font-family: " Roboto ", sans-serif;
  color: white;
  border-radius: 10px;
}
/* .faqsection .accordion {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-around;
  max-width: 1000px;
  width: 100%;
  border: 1px solid rgba(255, 255, 255, 0.18);
  height: auto;
  background-color: #EF0E52;
  border-radius: 10px;
  padding: 20px;
} */

.accordion{
  width: 100%;
}

.accordion h2 {
  text-align: center;
}

.accordion .contentbx {
  margin: 10px 20px;
  position: relative;
}

.accordion .contentbx .label {
  position: relative;
  padding: 15px;
  font-size: large;
  background: #FC0100;
  color: white;
  cursor: pointer;
}

.accordion .contentbx .label::before {
  content: "+";
  position: absolute;
  top: 50%;
  right: 20px;
  transform: translateY(-50%);
  font-size: 1.5rem;
  color: white;
}

.accordion .contentbx.active .label::before {
  content: "-";
}

.accordion .contentbx .content {
  position: relative;
  background: white;
  height: 0;
  overflow: hidden;
  transition: 0.5s;
  overflow-y: auto;
  font-size: large;
  color: black;
}

.accordion .contentbx.active .content {
  height: max-content;
  padding: 10px;
}
.carousel-control-next,
.carousel-control-prev /*, .carousel-indicators */ {
    filter: invert(100%);
}

.carousel-indicators [data-bs-target]{
  background-color: #FC0100;
}
/*# sourceMappingURL=contact.css.map */
</style>
    {% get_current_language as LANGUAGE_CODE %}
    {% if LANGUAGE_CODE == 'en' %}
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        {% for engsld in engslide %}
        <div class="carousel-item {% if forloop.counter0 == 0%} active {% endif %}">
          <img src="{{engsld.engslideimg.url}}" class="d-block w-100" alt="...">
        </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    {% else %}
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        {% for sld in slide %}
        <div class="carousel-item {% if forloop.counter0 == 0%} active {% endif %}">
          <img src="{{sld.slideimg.url}}" class="d-block w-100" alt="...">
        </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    {% endif %}
    <!-- BANNER WRAPPER -->
<!-- Mehsullar -->



<div class="container">
  <div class="row">
    <div class="col-lg-12 mt-5">
      <h2 class="fw-700  text-center mb-5 mt-5">
        {% translate 'Önə çıxan tikinti materialları' %}
      </h2>
    </div>
    {% for item in mainproduct %}
    <div class = 'col-lg-3 col-md-4 col-6'>
      <div class="col-lg-12 p-3 rounded-6 border my-3 posr">
        <a href="#" class="d-block text-center" data-bs-toggle="modal"
          data-bs-target="#productmodal"><img style="height: 200px;" src="{{ item.productimg.url }}" alt="product-image"
            class="w-100 mt-1 rounded_img d-inline-block" /></a>

        <div class="clearfix"></div>
        <div style="margin-top: 20px; height: 70px;">
        <h2 style="text-align: center;" >
          <a href="{% url 'goldapp:product' id=item.id %}"
            class="text-yellow item-name fw-600 lh-22  ls-0">{{ item.name}}
            <br />
           

          </a>
        </h2>
      </div>
      {% if item.is_approximate %}
        <div style="margin-top: 80px;" class="d-flex flex-row align-items-center justify-content-center">
          <h2 style="color: red; text-align: center;" class=" mb-0 ls-3 fw-700 ">
            {{ item.price }}  ₼ <span style="color: grey; font-size: 15px;">- dan</span>  
            
          </h2>
        </div>
        {% else %}
        <div style="margin-top: 80px;" class="d-flex flex-row align-items-center justify-content-center">
          <h2 style="color: red; text-align: center;" class=" mb-0 ls-3 fw-700 ">
            {{ item.price }}  ₼  
            
          </h2>
        </div>
        {% endif %}
       
      </div>
    </div>
    {% endfor %}

    <hr style="margin-top: 30px;">

    <div class="col-lg-12 mt-1">
      <h2 class="fw-700 font-xs text-center mb-5 mt-5">
        {% translate 'Ən son əlavə edilən məhsullar' %}
      </h2>
    </div>
    {% for item in dateproduct %}
    <div class = 'col-lg-3 col-md-4 col-6'>
      <div class="col-lg-12 p-3 rounded-6 border my-3 posr">
        <a href="#" class="d-block text-center" data-bs-toggle="modal"
          data-bs-target="#productmodal"><img style="height: 200px;" src="{{ item.productimg.url }}" alt="product-image"
            class="w-100 mt-1 rounded_img d-inline-block" /></a>

        <div class="clearfix"></div>
        <div style="margin-top: 20px; height: 70px;">
        <h2 style="text-align: center;" >
          <a href="{% url 'goldapp:product' id=item.id %}"
            class="text-yellow item-name fw-600 lh-22  ls-0">{{ item.name}}
            <br />
           

          </a>
        </h2>
      </div>
      {% if item.is_approximate %}
        <div style="margin-top: 80px;" class="d-flex flex-row align-items-center justify-content-center">
          <h2 style="color: red; text-align: center;" class=" mb-0 ls-3 fw-700 ">
            {{ item.price }}  ₼ <span style="color: grey; font-size: 15px;">- dan</span>  
            
          </h2>
        </div>
        {% else %}
        <div style="margin-top: 80px;" class="d-flex flex-row align-items-center justify-content-center">
          <h2 style="color: #FF0000; text-align: center;" class=" mb-0 ls-3 fw-700 ">
            {{ item.price }}  ₼  
            
          </h2>
        </div>
        {% endif %}
       
      </div>
    </div>
    {% endfor %}

    <hr style="margin-top: 30px;">
    <a style="font-size: x-large; text-decoration: underline; color: red;" class="fw-700 text-center mb-3 mt-3" href="{% url 'goldapp:allproducts' %}">{% translate 'Bütün məhsullara baxın' %}</a>
    <hr style="margin-top: 30px;">
  </div>
 </div>
 <!-- {% if newproduct|length > 0 %}
    <div class="d-pagination">
        <ul class="pagination justify-content-center">
      {% if newproduct.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ newproduct.previous_page_number }}"><i class="feather-chevron-left"></i></a>
        </li>
      {% endif %}
      {% for ord in newproduct.paginator.page_range %}
        {% if newnewproduct.number == ord %}
          <li class="page-item active">
            <span class="page-link">{{ ord }}
            </span>
          </li>
        {% elif ord > newproduct.number|add:'-3' and ord < newproduct.number|add:'3' %}
          <li class="page-item">
            <a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
          </li>

        {% endif %}

      {% endfor %}
       {% if newproduct.has_next %}
       
        <li class="page-item">
          <a class="page-link" href="?page={{ newproduct.paginator.num_pages }}"><i class="feather-chevron-right"></i></a>
        </li>
      {% endif %}
        </ul>
    </div>
    {% else %}
    <h3 class="text-center mt-5">Məhsul tapılmadı...</h3>
    {% endif %}	 	  -->
<br><br>
    <!-- <div class="banner-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12 m-0 p-0">
            <div
              class="owl-carousel slider-banner banner-wrap owl-theme ovh m-0 p-0 nav-none owl-arrow-center arrow-container">
            	{% for prsld in prod_slide %}
              <div class="item rounded-0  bg-image-cover ovh style1 d-flex justify-content-start" style="
                    background-image: url({{prsld.prodslideimg.url}})
                  ">
               <div  style="margin:100px;"></div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div> -->
    <!-- <h1 class="fw-700 text-center mb-5 mt-5">
      <i class="fa-solid fa-circle-question"></i>
        <span style="margin-left: 15px;"></span> Tez-tez soruşulan suallar
      </h1> -->
      <!-- {% for faq in faqs %}
      <section class="faqsection">
        <div class="accordion">
          <div class="contentbx">
            <div class="label">
              <div style="width: 95%;" class="questiontext">
                {{faq.question}}
              </div>
             </div>
            <div class="content">
              <p>
                 {{faq.answer}}
              </p>
            </div>
          </div>
        </div>
      </section>
      {% endfor %} -->


<!-- BANNER WRAPPER -->
<div class="container">
  <div class="row">
    <h1 class="font-xs text-center my-5">{% translate 'Bizim Partnyorlarımız' %}</h1>
    <section class="customer-logos mb-5  slider change_section">
      {% for prt in partnyor %}
      <div class="slide ">
        <img src="{{prt.partnyorimg.url}}" />
      </div>
      {% endfor %}
    </section>
  </div>

</div>

<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4993582619157234"
     crossorigin="anonymous"></script>
<!-- <script>
  const accordion = document.getElementsByClassName("contentbx");
  for (i = 0; i < accordion.length; i++) {
    accordion[i].addEventListener("click", function () {
      this.classList.toggle("active");
    });
  }
</script> -->
{% endblock %}

goldapp/templates/product.html
{% extends 'base.html' %}
{% load static i18n %}

{%block title %}{% translate 'Seçilən məhsul' %}{% endblock %}
{% block container %}


<!-- section -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <!--  Product Details -->
     
        <div class="col-md-6 mt-3 col-12">
          <div class="product product-details clearfix">
          <div id="product-main-view">
            {% for rs in images %}
            <div class="product-view">
              <img src="{{ rs.productimg.url }}" alt="">
            </div>
            {% endfor %}
            <div class="product-view ">
              <img src="{{ product.productimg.url }}" alt="">
            </div>

          </div>
          <div id="product-view">
            {% for rs in images %}
            <div class="product-view">
              <img src="{{ rs.productimg.url }}" alt="">
            </div>
            {% endfor %}
            <div class="product-view">
              <img src="{{ product.productimg.url }}" alt="">
            </div>
          </div>
        </div>
       
        </div>
        <div class="col-md-6 mt-3 col-12">
          <div class="product-card ">
            <h2 class="fw-700  font-xs ls-0 mt-2 tag-name lh-3">{{ product.name }}</h2>
      
            <div class="clearfix"></div>
            <p class="font-xssss fw-500 mt-0 text-grey-700 lh-24">{{ product.description }}</p>
            <div class="d-flex flex-row align-items-center mt-5 justify-content-between">
                <h3 style="color: red;" class=" ls-3 fw-700   float-start ">{{ product.price }} ₼</h3> 
            </div>
           
          </div>
      <!-- /Product Details -->
    </div>
  
  </div>
 
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /section

{% endblock %} -->